"""
BoBClaw Gateway — Configuration
Loads from ../.secrets/bobclaw.env or local .env
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Load env: check .secrets first, then local
_SECURE_ENV = Path(__file__).parent.parent / ".secrets" / "bobclaw.env"
_LOCAL_ENV = Path(__file__).parent / ".env"

# override=False: real process env (launchers / pytest conftest setdefault) wins
# over .secrets — prevents .secrets leaking into pytest. (Matches pipeline config.)
if _SECURE_ENV.exists():
    load_dotenv(_SECURE_ENV, override=False)
else:
    load_dotenv(_LOCAL_ENV)


# Secrets that are trivially guessable and must be rejected.
_SECRET_BLOCKLIST: frozenset[str] = frozenset(
    {"changeme", "secret", "password", "bobclaw", "none", ""}
)


class BoBClawGatewayConfig:
    """Gateway service configuration."""

    # -- Server --
    PORT: int = int(os.getenv("BOBCLAW_GATEWAY_PORT", "7826"))
    # Loopback by default. The gateway is the only service meant to face clients,
    # but it should still be reached over 127.0.0.1 (or a reverse proxy / SSH
    # tunnel you place in front of it), never bound to 0.0.0.0. See SECURITY.md.
    HOST: str = os.getenv("BOBCLAW_GATEWAY_HOST", "127.0.0.1")

    # -- TLS --
    TLS_ENABLED: bool = os.getenv("TLS_ENABLED", "false").lower() == "true"
    TLS_CERT: str = os.getenv("TLS_CERT", "ssl/cert.pem")
    TLS_KEY: str = os.getenv("TLS_KEY", "ssl/key.pem")

    # -- Auth --
    # Support both JWT_SECRET (gateway-specific) and BOBCLAW_SECRET (shared secret)
    JWT_SECRET: str = os.getenv("JWT_SECRET") or os.getenv("BOBCLAW_SECRET", "")
    # The SHARED secret core also reads (core.config.BOBCLAW_SECRET) — read explicitly
    # (not via the JWT_SECRET fallback) so the gateway→core scope vouch (Neck Beard P3)
    # is keyed on the same value on both sides even when a gateway-only JWT_SECRET is
    # set. Empty ⇒ the vouch is "" ⇒ core fails closed (scope not honored).
    BOBCLAW_SECRET: str = os.getenv("BOBCLAW_SECRET", "")
    # Admin password. Prefer BOBCLAW_PASSWORD_HASH (a bcrypt hash, generated by
    # scripts/gen_secrets.py) so the plaintext is never stored at rest. The plaintext
    # BOBCLAW_PASSWORD is still honored for backward compatibility when no hash is set.
    BOBCLAW_PASSWORD: str = os.getenv("BOBCLAW_PASSWORD", "")
    BOBCLAW_PASSWORD_HASH: str = os.getenv("BOBCLAW_PASSWORD_HASH", "")
    TOTP_SECRET: str = os.getenv("TOTP_SECRET", "")

    # -- Token lifetimes --
    ACCESS_TOKEN_MINUTES: int = int(os.getenv("ACCESS_TOKEN_MINUTES", "15"))
    # Per-token sliding TTL (rotation-on-use resets it). Shortened from 90 -> 30.
    REFRESH_TOKEN_DAYS: int = int(os.getenv("REFRESH_TOKEN_DAYS", "30"))
    # Absolute maximum age of a rotation CHAIN, measured from the first login.
    # Rotation cannot extend a chain past this, so a stolen refresh token cannot be
    # rotated indefinitely to live forever. Re-login is required after this.
    REFRESH_TOKEN_ABSOLUTE_DAYS: int = int(os.getenv("REFRESH_TOKEN_ABSOLUTE_DAYS", "90"))
    # Scoped agent (Neck Beard MODE) bearer tokens — standalone, non-refreshable
    # in v0. Longer-lived than the 15-min human access token because a headless
    # agent has no interactive refresh loop yet (Phase 5 adds revocation/refresh).
    AGENT_TOKEN_DAYS: int = int(os.getenv("AGENT_TOKEN_DAYS", "30"))

    # -- Rate limiting (in-memory; per-process) --
    RATE_LIMIT_PER_MINUTE: int = int(os.getenv("RATE_LIMIT_PER_MINUTE", "60"))
    RATE_LIMIT_BURST: int = int(os.getenv("RATE_LIMIT_BURST", "60"))

    # -- Login brute-force lockout (per-IP, persisted; B1) --
    # After LOGIN_MAX_FAILURES consecutive failed logins from an IP, lock it out with
    # exponential backoff (base doubling per extra failure, capped). Reset on success.
    LOGIN_MAX_FAILURES: int = int(os.getenv("LOGIN_MAX_FAILURES", "5"))
    LOGIN_LOCKOUT_BASE_SECONDS: int = int(os.getenv("LOGIN_LOCKOUT_BASE_SECONDS", "30"))
    LOGIN_LOCKOUT_MAX_SECONDS: int = int(os.getenv("LOGIN_LOCKOUT_MAX_SECONDS", "900"))

    # -- CORS --
    ALLOWED_ORIGINS: list[str] = [
        origin.strip()
        for origin in os.getenv("ALLOWED_ORIGINS", "").split(",")
        if origin.strip()
    ]

    # -- Upstream services --
    CORE_URL: str = os.getenv("CORE_URL", "http://localhost:7825")
    CLAUDE_PIPELINE_URL: str = os.getenv("CLAUDE_PIPELINE_URL", "http://localhost:7823")
    CANOPY_URL: str = os.getenv("CANOPY_URL", "http://localhost:7822")

    # -- Database --
    POSTGRES_URL: str = os.getenv(
        "POSTGRES_URL", "postgresql://bobclaw:bobclaw@localhost:5432/bobclaw"
    )

    # -- Redis (pub/sub for live approval notifications) --
    REDIS_URL: str = os.getenv("REDIS_URL", "redis://localhost:6379/0")

    # -- Logging --
    LOG_LEVEL: str = os.getenv("LOG_LEVEL", "INFO")

    # -- History replay (trailing-N context for conversation continuity) --
    HISTORY_MESSAGE_COUNT: int = int(os.getenv("BOBCLAW_HISTORY_MESSAGES", "20"))
    HISTORY_MAX_CHARS: int = int(os.getenv("BOBCLAW_HISTORY_MAX_CHARS", "8192"))

    # -- Audit logging --
    AUDIT_LOG_ENABLED: bool = os.getenv("AUDIT_LOG_ENABLED", "true").lower() == "true"

    @classmethod
    def validate(cls) -> None:
        """Validate required configuration. Raises ValueError on missing fields."""
        errors = []

        # JWT_SECRET
        if not cls.JWT_SECRET:
            errors.append("JWT_SECRET (or BOBCLAW_SECRET) is required")
        else:
            if len(cls.JWT_SECRET) < 32:
                errors.append("JWT_SECRET must be at least 32 characters")
            if cls.JWT_SECRET.lower() in _SECRET_BLOCKLIST:
                errors.append(f"JWT_SECRET is too common / placeholder: {cls.JWT_SECRET!r}")

        # Admin password — require a plaintext OR a bcrypt hash (the hash is preferred;
        # gen_secrets.py writes BOBCLAW_PASSWORD_HASH). Plaintext stays valid for back-compat.
        if not cls.BOBCLAW_PASSWORD and not cls.BOBCLAW_PASSWORD_HASH:
            errors.append("BOBCLAW_PASSWORD or BOBCLAW_PASSWORD_HASH is required")
        if cls.BOBCLAW_PASSWORD and cls.BOBCLAW_PASSWORD.lower() in _SECRET_BLOCKLIST:
            errors.append(
                f"BOBCLAW_PASSWORD is too common / placeholder: {cls.BOBCLAW_PASSWORD!r}"
            )

        # TOTP_SECRET
        if not cls.TOTP_SECRET:
            errors.append("TOTP_SECRET is required")
        if cls.TOTP_SECRET and len(cls.TOTP_SECRET) < 16:
            errors.append("TOTP_SECRET must be at least 16 characters")
        if cls.TOTP_SECRET and cls.TOTP_SECRET.lower() in _SECRET_BLOCKLIST:
            errors.append(
                f"TOTP_SECRET is too common / placeholder: {cls.TOTP_SECRET!r}"
            )

        # CORS origins — reject a wildcard or a malformed entry. A bare '*' would
        # be handed straight to aiohttp_cors and allow every site to call the API.
        for origin in cls.ALLOWED_ORIGINS:
            if "*" in origin:
                errors.append(
                    f"ALLOWED_ORIGINS may not contain a wildcard: {origin!r}"
                )
            elif not (origin.startswith("http://") or origin.startswith("https://")):
                errors.append(
                    f"ALLOWED_ORIGINS entry must be a scheme://host URL: {origin!r}"
                )

        if errors:
            raise ValueError(f"Config errors: {'; '.join(errors)}")


config = BoBClawGatewayConfig()
